keypress_delay_ms: 20

modmap:
  - name: Global
    remap:
      # CapsLock
      CAPSLOCK: Rightmeta


  - name: IME
    remap:
      LEFTALT:
        held: Alt_L
        alone: Muhenkan
        alone_timeout_millis: 300
      RIGHTALT:
        held: Alt_R
        alone: Henkan
        alone_timeout_millis: 300
